apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
  - name: my-container-app
    image: docker.io/bhuvansuresh09/nodejs-application:v1
    ports:
    - containerPort: 8080
    env:
    - name: PROMETHEUS_PORT
      value: "8081"
  - name: prometheus
    image: prom/prometheus:v2.27.1
    args:
    - --config.file=/etc/prometheus/prometheus.yaml
    - --web.enable-admin-api
    ports:
    - containerPort: 9090
    volumeMounts:
    - name: prometheus-config
      mountPath: /etc/prometheus/
      readOnly: true
  volumes:
  - name: prometheus-config
    configMap:
      name: prometheus-configmap
      items:
      - key: prometheus.yaml
        path: prometheus.yaml

